import os

OPENCAGE_API_KEY = os.environ.get("OPENCAGE_API_KEY")
OPENWEATHER_API_KEY = os.environ.get("OPENWEATHER_API_KEY")
TOMORROW_API_KEY = os.environ.get("TOMORROW_API_KEY")

print("ENV DEBUG:")
print("OPENCAGE:", OPENCAGE_API_KEY)
print("OPENWEATHER:", OPENWEATHER_API_KEY)
print("TOMORROW:", TOMORROW_API_KEY)